#!/bin/bash
################################################################################
# Microsoft Graph MCP Server - Manual Installation Steps
# Run these commands one at a time
################################################################################

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Microsoft Graph MCP Server - Manual Installation           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Please run these commands to install .NET SDK:"
echo ""
echo "1. Download Microsoft package repository configuration:"
echo "   wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O /tmp/packages-microsoft-prod.deb"
echo ""
echo "2. Install the repository configuration:"
echo "   sudo dpkg -i /tmp/packages-microsoft-prod.deb"
echo ""
echo "3. Clean up:"
echo "   rm /tmp/packages-microsoft-prod.deb"
echo ""
echo "4. Update package list:"
echo "   sudo apt-get update"
echo ""
echo "5. Install .NET SDK 9.0:"
echo "   sudo apt-get install -y dotnet-sdk-9.0"
echo ""
echo "6. Verify installation:"
echo "   dotnet --version"
echo ""
echo "7. Build the MCP server:"
echo "   cd /home/bmoore/Projects/microsoft-graph-mcp/McpServerGraphAPI"
echo "   dotnet restore"
echo "   dotnet build"
echo ""
echo "8. Test the server:"
echo "   dotnet run"
echo ""
echo "╚══════════════════════════════════════════════════════════════╝"
